using KmcEvents.Client.Filters;
using KmcEvents.Client.Models;
using KmcEvents.Client.Services;

using Microsoft.AspNetCore.Mvc;

namespace KmcEvents.Client.Controllers;

// ============================================================
// KMC ADMIN CONTROLLER
// Handles dashboard, users, events, reservations,
// reports, PDF download and system activity.
// ============================================================

[SessionAuthorize("KMC Admin")]
public class AdminController : Controller
{
    private readonly ApiClient _api;

    public AdminController(ApiClient api)
    {
        _api = api;
    }

    // ========================================================
    // ADMIN DASHBOARD
    // ========================================================

    public async Task<IActionResult> Dashboard()
    {
        var users = await _api.GetAsync<List<UserRowVm>>(
            "admin/users"
        ) ?? new List<UserRowVm>();

        var events = await _api.GetAsync<List<AdminEventRowVm>>(
            "admin/events"
        ) ?? new List<AdminEventRowVm>();

        var reservations = await _api.GetAsync<List<ReservationVm>>(
            "admin/reservations"
        ) ?? new List<ReservationVm>();

        var dashboard = await _api.GetAsync<AdminDashboardVm>(
            "admin/dashboard"
        ) ?? new AdminDashboardVm();

        ViewBag.Users = users;
        ViewBag.Events = events;
        ViewBag.Reservations = reservations;

        return View(dashboard);
    }

    // ========================================================
    // MANAGE ALL EVENTS
    // ========================================================

    public async Task<IActionResult> Events()
    {
        var events = await _api.GetAsync<List<AdminEventRowVm>>(
            "admin/events"
        ) ?? new List<AdminEventRowVm>();

        return View(events);
    }

    // ========================================================
    // MANAGE ALL RESERVATIONS
    // ========================================================

    public async Task<IActionResult> Reservations()
    {
        var reservations = await _api.GetAsync<List<ReservationVm>>(
            "admin/reservations"
        ) ?? new List<ReservationVm>();

        return View(reservations);
    }

    // ========================================================
    // REPORTS
    // Loads monthly revenue,
    // public user participation
    // and organizer income.
    // ========================================================

    public async Task<IActionResult> Reports()
    {
        var monthlyRevenue = await _api.GetAsync<List<MonthlyRevenueVm>>(
            "admin/reports/monthly-revenue"
        ) ?? new List<MonthlyRevenueVm>();

        var publicUsers = await _api.GetAsync<List<PublicUserReportVm>>(
            "admin/reports/public-users"
        ) ?? new List<PublicUserReportVm>();

        var organizers = await _api.GetAsync<List<OrganizerIncomeVm>>(
            "admin/reports/organizers"
        ) ?? new List<OrganizerIncomeVm>();

        ViewBag.MonthlyRevenue = monthlyRevenue;
        ViewBag.PublicUsers = publicUsers;
        ViewBag.Organizers = organizers;

        return View();
    }

    // ========================================================
    // DOWNLOAD ADMIN PDF REPORT
    // Downloads the complete report generated by the API.
    // ========================================================

    public async Task<IActionResult> DownloadReportPdf()
    {
        var pdf = await _api.GetBytesAsync(
            "admin/reports/pdf"
        );

        if (pdf == null || pdf.Length == 0)
        {
            TempData["Error"] =
                "Unable to generate PDF report.";

            return RedirectToAction(
                nameof(Reports)
            );
        }

        var fileName =
            $"KMC_Admin_Report_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";

        return File(
            pdf,
            "application/pdf",
            fileName
        );
    }

    // ========================================================
    // SYSTEM ACTIVITY
    // Will be connected after SystemActivity is implemented.
    // ========================================================

    public IActionResult Activity()
    {
        return View();
    }

    // ========================================================
    // DISABLE USER
    // API changes account status and sends email notification.
    // ========================================================

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DisableUser(int id)
    {
        var result = await _api.SendAsync<ApiMessage>(
            HttpMethod.Patch,
            $"admin/users/{id}/active?value=false"
        );

        if (result.ok)
            TempData["Success"] = result.message;
        else
            TempData["Error"] = result.message;

        return RedirectToAction(
            nameof(Dashboard)
        );
    }

    // ========================================================
    // ENABLE USER
    // API changes account status and sends email notification.
    // ========================================================

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EnableUser(int id)
    {
        var result = await _api.SendAsync<ApiMessage>(
            HttpMethod.Patch,
            $"admin/users/{id}/active?value=true"
        );

        if (result.ok)
            TempData["Success"] = result.message;
        else
            TempData["Error"] = result.message;

        return RedirectToAction(
            nameof(Dashboard)
        );
    }

    // ========================================================
    // CONTACT MESSAGES
    // ========================================================

    public async Task<IActionResult> Messages()
    {
        var messages = await _api.GetAsync<List<ContactMessageVm>>(
            "admin/contact-messages"
        ) ?? new List<ContactMessageVm>();

        return View(messages);
    }
}